export enum CardRarity {
  Unknown = 0,
  Common = 1,
  Uncommon = 2,
  AmazingRare = 3,
  Legend = 4,
  Promo = 5,
  Rare = 6,
  RareAce = 7,
  RareBreak = 8,
  RareHolo = 9,
  RareHoloEx = 10,
  RareHoloGx = 11,
  RareHoloLvX = 12,
  RareHoloStar = 13,
  RareHoloV = 14,
  RareHoloVMax = 15,
  RarePrime = 16,
  RatePrismStar = 17,
  RareRainbow = 18,
  RareSecret = 19,
  RareShining = 20,
  RareShiny = 21,
  RareShinyGx = 22,
  RareUltra = 23
}